name: Chronicler
version: '1.2.1'
main: uk.ewancroft.chronicler.Chronicler
api-version: '1.21'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false

commands:
  chronicler:
    description: Chronicler commands.
    aliases: [clr]
    permission: chronicler.use

permissions:
  chronicler.use:
    description: Read the newspaper.
    default: true
  chronicler.admin:
    description: Admin commands for Chronicler.
    default: op
