name: Chronicler
version: '${version}'
main: uk.ewancroft.chronicler.Chronicler
api-version: '1.21'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
