name: Chronicler
version: '${version}'
main: uk.ewancroft.chronicler.Chronicler
api-version: '1.21'
description: Tracks server events and generates a dynamic newspaper.
author: ewanc26
softdepend: [PlaceholderAPI, Vault, ViaVersion, floodgate, BlueMap, squaremap, Towny, Lands, LuckPerms, mcMMO, QuickShop-Hikari, Plan, Votifier, DiscordSRV]

commands:
  chronicler:
    description: Chronicler commands.
    aliases: [clr]
    permission: chronicler.use

permissions:
  chronicler.use:
    description: Read the newspaper.
    default: true
  chronicler.write:
    description: Send letters to the editor and classified adverts.
    default: true
  chronicler.admin:
    description: Admin commands for Chronicler.
    default: op
